set nocompatible
filetype off
set rtp+=~/.vim/bundle/vundle
call vundle#rc()

Plugin 'gmarik/vundle'
Plugin 'thoughtbot/vim-rspec'

filetype plugin indent on

syntax enable
colorscheme molokai

set number
set showcmd
set cursorline

set complete+=kspell

set smartindent
set tabstop=2
set shiftwidth=2
set expandtab

:let mapleader=","

map <leader>f :call RunCurrentSpecFile()<cr>
map <leader>s :call RunNearestSpec()<cr>
map <leader>l :call RunLastSpec()<cr>
map <leader>a :call RunAllSpecs()<cr>

augroup configgroup
  autocmd BufEnter Makefile setlocal noexpandtab
  autocmd FileType java setlocal tabstop=4 shiftwidth=4
  autocmd FileType ruby source ~/.vim/ruby.vim
  autocmd BufNewFile,BufRead COMMIT_EDITMSG setlocal spell
augroup END
